### PR TITLE
UI changes and enhancements for paper-wallet

### PR DESCRIPTION
**Pull request by ahumblenerd**
## Updates in DEV Branch

* Revamped the UI.
* Added ability to download the paper wallet as PDF.

## Screenshots
screen shot 2018-01-01 at 11 31 11 pm

screen shot 2018-01-01 at 11 26 13 pm

### CODE REVIEW

**Comment by ahumblenerd** [comment]
@stellar-slackbot : Can someone please review this PR and give me some suggestions ? 
@bartekn : Please review this.

**Review by ruudsnl — COMMENTED** [review]
Very nice! But why is the non-minified uikit.js and uikit-icons.js used?

**Comment by kfiresmith** [comment]
This is a welcome formatting change.  
For those who might prefer Python, we're working on a similar one inspired by some PNG files shared on reddit a few weeks ago here:
https://github.com/xaviablaza/stellar-paper-wallet

**Comment by ahumblenerd** [comment]
@ruudschuurmans  I will make the changes and update asap.

**Comment by ahumblenerd** [comment]
@kfiresmith Python head here. Will take a look into this 👍

**Comment by bartekn** [comment]
Project no longer maintained: https://stellar.github.io/paper-wallet/

**Pull request closed without merging**
