### PR TITLE
Deprecate this tool

### PR DESCRIPTION
**Pull request by bartekn**
Switch to `stellar-hd-wallet`. It's just much easier to store and do not require a printer.

### CODE REVIEW

**Comment by kfiresmith** [comment]
Probably you could adopt the superior Python based paper wallet generator into the project so that folks still have the easy option to promote Stellar to new users :)
https://github.com/xaviablaza/stellar-paper-wallet

**Comment by ahumblenerd** [comment]
@bartekn  I contributed thinking that paper wallets are safer than any other form. Ledger Nano costs 12k ( In India ). So for users like me, paper wallet is way more safer and affordable. A print costs us Rs 2 ($ 0.031 ). I will checkout the suggestion. 👍

**Comment by kfiresmith** [comment]
Bummer and a miss-step to be sure.  There are superior wallets out there for Stellar but nobody within the Stellar Core team even tried to bring one into the fold.  Very disappointing to see how this topic was fumbled.

**Comment by bartekn** [comment]
@kfiresmith please create a PR that adds a footnote with a link to your project and I'll be happy to merge this. Something like:
> If you still want to use a paper wallet try: [url] (not maintained by SDF)

**Pull request merged**
